### PR TITLE
fix: optimize insertions in building when lists = 1

### PR DESCRIPTION
**Pull request by usamoi**

### CODE REVIEW

**Comment by kemingy** [comment]
If you change the toolchain version, you may need to update the image. I'll create a CI to push the image to GitHub packages so developers can trigger the CI to update the image.

**Comment by usamoi** [comment]
> If you change the toolchain version, you may need to update the image. I'll create a CI to push the image to GitHub packages so developers can trigger the CI to update the image.

Why do we need to update the image? Why not add targets when image is used?

**Comment by kemingy** [comment]
> > If you change the toolchain version, you may need to update the image. I'll create a CI to push the image to GitHub packages so developers can trigger the CI to update the image.
> 
> Why do we need to update the image? Why not add targets when image is used?

Adding targets later means you need to do it for every docker image run. Updating the version is not a highly frequent operation.

**Comment by usamoi** [comment]
> > > If you change the toolchain version, you may need to update the image. I'll create a CI to push the image to GitHub packages so developers can trigger the CI to update the image.
> > 
> > 
> > Why do we need to update the image? Why not add targets when image is used?
> 
> Adding targets later means you need to do it for every docker image run. Updating the version is not a highly frequent operation.

I think adding a target takes less than one second on Github actions and downloading the docker image takes more than one. If we want it to be faster, we should remove docker for first.

**Comment by usamoi** [comment]
I just noticed that sqllogictest tests does not run on all PostgreSQL major versions.

**Comment by kemingy** [comment]
Adding targets costs about 17.8s in GitHub CI. Downloading the whole image is about 53s for now, almost the same as downloading from Docker Hub. ~~I thought accessing ghcr should be much faster.~~

**Comment by usamoi** [comment]
> Adding targets costs about 17.8s in GitHub CI.

Screenshot_20241121_204825

Their servers must be on the moon or Mars. It takes only 4 seconds even on my machine.

**Pull request merged**
